import React, { useState, useRef } from 'react';
import { PageTitle, Tab, TabGroup, ActionButton, LoadingState, ErrorState, EmptyState } from '../components/shared';
import { MaterialSymbol, SparklesIcon } from '../components/icons';
import { GoogleGenAI, Modality } from '@google/genai';
import { fileToBase64 } from '../utils/media';
import ReactMarkdown from 'https://esm.sh/react-markdown@9';
import remarkGfm from 'https://esm.sh/remark-gfm@4';


type ActiveTab = 'generate' | 'edit' | 'analyze';

const ImageStudio: React.FC = () => {
    const [activeTab, setActiveTab] = useState<ActiveTab>('generate');
    const [prompt, setPrompt] = useState('');
    const [aspectRatio, setAspectRatio] = useState('1:1');
    const [imageFile, setImageFile] = useState<File | null>(null);
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);
    const [result, setResult] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setImageFile(file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setPreviewUrl(reader.result as string);
            };
            reader.readAsDataURL(file);
            setResult(null);
            setError(null);
        }
    };

    const resetState = () => {
        setPrompt('');
        setImageFile(null);
        setPreviewUrl(null);
        setResult(null);
        setIsLoading(false);
        setError(null);
    }

    const handleTabChange = (tab: ActiveTab) => {
        setActiveTab(tab);
        resetState();
    }
    
    const getAi = () => new GoogleGenAI({ apiKey: process.env.API_KEY! });

    const handleGenerate = async () => {
        if (!prompt) return;
        setIsLoading(true);
        setError(null);
        setResult(null);

        try {
            const ai = getAi();
            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt,
                config: {
                    numberOfImages: 1,
                    outputMimeType: 'image/jpeg',
                    aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
                },
            });
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            setResult(`data:image/jpeg;base64,${base64ImageBytes}`);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'An unknown error occurred.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleEdit = async () => {
        if (!prompt || !imageFile) return;
        setIsLoading(true);
        setError(null);
        setResult(null);

        try {
            const ai = getAi();
            const imageBase64 = await fileToBase64(imageFile);
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: { parts: [ { inlineData: { data: imageBase64, mimeType: imageFile.type } }, { text: prompt } ] },
                config: { responseModalities: [Modality.IMAGE] },
            });
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    setResult(`data:${part.inlineData.mimeType};base64,${part.inlineData.data}`);
                    return;
                }
            }
            throw new Error('No image was generated by the model.');
        } catch (err) {
            setError(err instanceof Error ? err.message : 'An unknown error occurred.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleAnalyze = async () => {
        if (!prompt || !imageFile) return;
        setIsLoading(true);
        setError(null);
        setResult(null);
        
        try {
            const ai = getAi();
            const imageBase64 = await fileToBase64(imageFile);
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: { parts: [ { inlineData: { data: imageBase64, mimeType: imageFile.type } }, { text: prompt } ] },
            });
            setResult(response.text);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'An unknown error occurred.');
        } finally {
            setIsLoading(false);
        }
    };
    
    const ImageUploadArea = () => (
        <div 
            className="w-full h-48 bg-gray-800/50 rounded-lg border-2 border-dashed border-gray-600 flex items-center justify-center text-center cursor-pointer hover:border-cyan-500 transition-colors"
            onClick={() => fileInputRef.current?.click()}
        >
            {previewUrl ? (
                <img src={previewUrl} alt="Preview" className="max-h-full max-w-full rounded-md" />
            ) : (
                <div className="text-gray-400">
                    <MaterialSymbol icon="upload_file" className="text-4xl" />
                    <p>Click to upload an image</p>
                </div>
            )}
            <input type="file" accept="image/*" ref={fileInputRef} onChange={handleFileChange} className="hidden" />
        </div>
    );

    const renderTabContent = () => {
        const isGenerate = activeTab === 'generate';
        const isEdit = activeTab === 'edit';
        const isAnalyze = activeTab === 'analyze';
        
        const canSubmit = prompt && (isGenerate || (imageFile && (isEdit || isAnalyze)));
        const handleSubmit = isGenerate ? handleGenerate : isEdit ? handleEdit : handleAnalyze;

        return (
            <div className="flex-grow flex flex-col md:flex-row gap-8">
                <div className="md:w-1/3 flex flex-col gap-4">
                    {!isGenerate && <ImageUploadArea />}
                    <textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder={isGenerate ? "A photorealistic image of..." : isEdit ? "Add a retro filter..." : "What is happening in this image?"} className="w-full flex-grow bg-gray-800 border border-gray-600 rounded-lg p-3 text-sm focus:ring-cyan-500 focus:border-cyan-500 transition resize-none" rows={isGenerate ? 8: 4} />
                    {isGenerate && (
                        <div>
                            <label className="text-sm font-medium text-gray-300 mb-2 block">Aspect Ratio</label>
                            <select value={aspectRatio} onChange={e => setAspectRatio(e.target.value)} className="w-full bg-gray-700 border-gray-600 rounded-md py-2 px-2 text-sm focus:ring-cyan-500 focus:border-cyan-500">
                                <option value="1:1">Square (1:1)</option>
                                <option value="16:9">Landscape (16:9)</option>
                                <option value="9:16">Portrait (9:16)</option>
                                <option value="4:3">Standard (4:3)</option>
                                <option value="3:4">Tall (3:4)</option>
                            </select>
                        </div>
                    )}
                    <ActionButton onClick={handleSubmit} isLoading={isLoading} disabled={!canSubmit} icon={<SparklesIcon className="-ml-1 mr-2 h-5 w-5"/>}>{isGenerate ? 'Generate' : isEdit ? 'Edit' : 'Analyze'}</ActionButton>
                </div>
                <div className="flex-grow md:w-2/3">
                    {isLoading && <LoadingState message="AI is thinking..." />}
                    {error && <ErrorState error={error} />}
                    {!isLoading && !error && !result && <EmptyState title="Output will appear here" message={isGenerate ? "Enter a prompt and click Generate to create an image." : "Upload an image and enter a prompt to get started."} icon={<MaterialSymbol icon="image" className="text-5xl text-gray-500" />} />}
                    {result && (
                        isAnalyze ? (
                            <div className="bg-gray-800/50 rounded-lg p-4 h-full overflow-y-auto prose prose-invert prose-sm max-w-none">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>{result}</ReactMarkdown>
                            </div>
                        ) : (
                            <div className="w-full h-full flex items-center justify-center bg-gray-800/30 rounded-xl p-4">
                                <img src={result} alt="Generated result" className="max-h-full max-w-full rounded-md shadow-lg"/>
                            </div>
                        )
                    )}
                </div>
            </div>
        );
    };

    return (
        <div className="flex flex-col h-full">
            <PageTitle title="Image Studio" subtitle="Generate, edit, and analyze images with powerful AI." />
            <TabGroup>
                <Tab label="Generate" isActive={activeTab === 'generate'} onClick={() => handleTabChange('generate')} />
                <Tab label="Edit" isActive={activeTab === 'edit'} onClick={() => handleTabChange('edit')} />
                <Tab label="Analyze" isActive={activeTab === 'analyze'} onClick={() => handleTabChange('analyze')} />
            </TabGroup>
            {renderTabContent()}
        </div>
    );
};

export default ImageStudio;
